---
title: "ggplot1"
output: github_document
---
```{r}
library(tidyverse)
library(patchwork)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)
```
#load a dataset that we'll use often
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

# Scatterplot
tmax vs. tmin
```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color = name)) +
  geom_point(alpha = 0.3) + 
  geom_smooth(se = FALSE) +
  facet_grid(.~ name)
```

```{r}
weather_df %>% 
  ggplot(aes(x=date, y=tmax, size = prcp)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se=FALSE) +
  facet_grid(.~ name)
```
#Remember this plot

```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color = name))+
  geom_point(alpha = 0.3)
```
#Labels

```{r, figwidth = 12}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color = name))+
  geom_point(alpha = 0.3) +
  labs(
    title = "Temperature Plot",
    x = "Minimum Daily Temperature (C)",
    y = "Maximum Daily Temperature (C)",
    caption = "data from RNOA package"
  )
```

#Scales
```{r, figwidth = 12}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color = name))+
  geom_point(alpha = 0.3) +
  labs(
    title = "Temperature Plot",
    x = "Minimum Daily Temperature (C)",
    y = "Maximum Daily Temperature (C)",
    caption = "data from RNOA package"
  ) + 
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15 ยบ C", "0", "15")
  ) +
  scale_y_continuous(
    trans = "sqrt"
  )
```
